#! /usr/bin/env bash

source "$HOMEgfs/ush/preamble.sh"

echo "$(date -u) begin ${BASH_SOURCE}"

set -xa
if [[ ${STRICT:-NO} == "YES" ]]; then
	# Turn on strict bash error checking
	set -eu
fi
export PS4='$SECONDS + $(basename ${BASH_SOURCE})[$LINENO] '

#############################
# Source relevant config files
#############################
export EXPDIR=${EXPDIR:-$HOMEgfs/parm/config}
configs="base epos"
config_path=${EXPDIR:-$NWROOT/gfs.${gfs_ver}/parm/config}
for config in $configs; do
    . $config_path/config.$config
    status=$?
    [[ $status -ne 0 ]] && exit $status
done

####################################
# Determine Job Output Name on System
####################################
export pid=${pid:-$$}
export job="gefs_prdgen"
export PBS_JOBID=${jobid:-${pid}}
export jobid=${jobid:-"$job.$PBS_JOBID"}
export pgmout="OUTPUT.${PBS_JOBID}"
export pgmerr=errfile

####################################
# Specify and create working directory
####################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir -p $DATA
cd $DATA

######################################
# Set up compute resources
######################################
export total_tasks=${total_tasks:-4}
#export APRUN_MPMD=${gefsmpexec_mpmd:-"mpiexec -n $total_tasks cfp mpmd_cmdfile"}
export gefsmpexec_mpmd="srun -n $total_tasks /scratch2/NCEPDEV/ensemble/noscrub/common/soft/mpiserial.cd/mpiserial"
export APRUN_MPMD=${gefsmpexec_mpmd:-"mpiexec --cpu-bind core --configfile mpmd_cmdfile"}

# The following options are fore re-forecast
export save_pgrb2_p5=${save_pgrb2_p5:-NO} 
export save_pgrb2_p25=${save_pgrb2_p25:-NO}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gefs}
export envir=${envir:-prod}
export RUN=${RUN:-gefs}

######################################
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
# SENDECF  - Flag Events on ECF
# VERBOSE  - Specify Verbose Output
######################################

export SENDCOM=YES
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export VERBOSE=${VERBOSE:-YES}

######################################
# Set up the date information
######################################
export cycle=t${cyc}z
setpdy.sh
source PDY

if [ ${FORECAST_SEGMENT:-hr} = lr ]; then
    export cyc=00
    export cycle=t${cyc}z
fi

####################################
# Specify Execution Areas
####################################
export HOMEgefs=$HOMEgfs
export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
export USHgefs=${USHgefs:-$HOMEgefs/ush}
export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
export PARMgefs=${PARMgefs:-$HOMEgefs/parm}

##############################################
# Define COM directories
##############################################
#ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
#export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
#export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}


#############################
# Source relevant config files
#############################
#configs="gefs gefs_prdgen"
#config_path=$PARMgefs
#for config in $configs; do
#    . $config_path/$config.parm
#    export err=$?
#    if [[ $err != 0 ]]; then
#        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
#        exit $err
#    fi
#done

#export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})/gfs.${PDY}/$cyc/atmos}

if [[ $cplchm = ".true." ]]; then
    COMPONENT="chem"
fi
export COMPONENT=${COMPONENT:-atmos}

export COMIN="$ROTDIR/gefs.$PDY/$cyc/${RUNMEM}"
export COMOUT="$ROTDIR/gefs.$PDY/$cyc/${RUNMEM}"

echo "Environment before calling script"
env | sort

#############################################################
# Execute the script
source $HOMEgefs/scripts/exgefs_atmos_prdgen.sh
export err=$?
if [[ $err == 0 ]]; then
    echo "$job completed normally!"
else
    echo "FATAL ERROR in ${BASH_SOURCE}: $job failed!"
    exit $err
fi
#############################################################

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

echo "$(date -u) end ${BASH_SOURCE}"

exit $err
